ellanetworks/core

internal/smf/qos/qos_flow.go
internal/smf/qos/qos_rule.go
internal/upf/core/sdf_filter_parser.go
internal/util/flowdesc/flowdesc.go

Fixes [https://github.com/ellanetworks/core/security/code-scanning/34](https://github.com/ellanetworks/core/security/code-scanning/34)
To fix the problem, we need to ensure that the integer value parsed from the string fits within the bounds of the `uint8` type before performing the conversion. This can be achieved by using `strconv.ParseUint` with a bit size of 8, which directly parses the string into a `uint8` value and ensures it is within the valid range.
- Replace the use of `strconv.Atoi` with `strconv.ParseUint` specifying a bit size of 8.
- Update the code to handle the returned `uint64` type from `strconv.ParseUint` and convert it to `uint8`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: fix incorrect conversion between integer types

---

docs/CNAME
docs/reference/tls.md
mkdocs.yml

Add CNAME file to docs root dir so that the CNAME configuration persists.  This fixes an issue where the custom domain configuration would be overwritten on every push to main.

fix: add CNAME file to docs root dir

---

internal/amf/amf.go
internal/amf/gmm/handler.go
internal/amf/gmm/message/send.go
internal/amf/ngap/dispatcher.go
internal/amf/ngap/handler.go
internal/amf/ngap/message/build.go
internal/amf/ngap/message/send.go
internal/amf/ngap/service/service.go
internal/amf/producer/n1n2message.go
internal/api/api.go
internal/ausf/ue_authentication.go

We keep on improving error handling in the AMF code. Specifically sending ngap messages return errors when there's an issue with the send operation (instead of logging) and the caller decides what to do with the error. There's still a long way to go in terms of improving error handling, but this is a step in the right direction. Next step is to do the same for the GMM code.

chore: improve error handling in amf

---

cmd/core/main.go
docs/reference/config_file.md
docs/reference/tls.md
internal/api/api.go
internal/api/api_test.go
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/valid_no_tls.yaml

Users who use ingresses or service meshes often prefer to have TLS terminated prior to reaching the workload. For those use-cases, it makes sense to start Ella Core without TLS. For any other use case, TLS remains strongly recommended. Here we make the use of TLS optional.
Fixes #500

feat: make TLS optional on the API interface

---

ui/app/(auth)/login/page.tsx

Since we now allow users to run Ella Core in `http` mode, we should also allow the UI to set cookies in non secure environments. Here we remove the `secure` from the setCookie call.

fix: set cookie on http connections

---

client/subscribers.go
docs/reference/api/subscribers.md
integration/integration_test.go
internal/api/server/api_subscribers.go
internal/api/server/api_subscribers_test.go
ui/components/CreateSubscriberModal.tsx
ui/queries/subscribers.tsx

Ella Core manages Operator Code (OP) centrally. When users create a subscriber, they provide a Key, and Ella Core uses that key and its central OP to generate the OPc. 
Some SIM vendors come with a pre-written OPc and Key. If users want to use those SIM cards, they would have to re-write them with the OPc provided by Ella Core, making the process of emitting cards more tedious than necessary.
Here we add the ability for users to specify the OPc of their choice. This is an optional feature, if users don't select it, Ella Core will generate the OPc.
Fixes #518

feat: allow user specified opc

---

docs/how_to/install.md
ui/components/ViewSubscriberModal.tsx

The Clipboard API is only available over HTTPS. Here we make it clearer why the copy behavior doesn't work.

fix: show alert when using clipboard copy over non-secure connection

---

ui/components/CreateSubscriberModal.tsx

Allow empty opc in create subscriber modal
Fixes #535

fix: allow empty opc in create subscriber modal

---

README.md
docs/index.md
docs/reference/performance.md

Add performance results from testing with [ella core tester](https://github.com/ellanetworks/core-tester) and iperf3
**Note**: I was able to get higher performance results, often over 3.50 Gbps (upstream) but I wasn't able to reproduce it consistently. I used the more conservative results.

docs: add performance results from testing with ella core tester

---

internal/api/api.go
internal/api/server/api_auth_test.go
internal/api/server/api_backup_test.go
internal/api/server/api_helpers_test.go
internal/api/server/api_operator_test.go
internal/api/server/api_profiles_test.go
internal/api/server/api_radios_test.go
internal/api/server/api_restore_test.go
internal/api/server/api_routes_test.go
internal/api/server/api_status_test.go
internal/api/server/api_subscribers_test.go
internal/api/server/api_users_test.go
internal/api/server/benchmark_test.go
internal/api/server/rate_limiter_middleware.go
internal/api/server/rate_limiter_middleware_test.go
internal/api/server/server.go
internal/db/db.go
internal/db/operator.go
internal/smf/context/upf.go
internal/smf/qos/qos_rule_test.go

This PR includes these 2 fixes:
- Only allow operator to be initialized once
- Allow 100 requests per second in rate-limiter
Fixes #590

fix: only allow operator to be initialized once

---

.github/workflows/ui-lint.yaml

Potential fix for [https://github.com/ellanetworks/core/security/code-scanning/82](https://github.com/ellanetworks/core/security/code-scanning/82)
To fix the issue, add a `permissions` block to the root of the workflow file. This block will explicitly limit the permissions of the `GITHUB_TOKEN` to the least privilege required for the workflow. Since the workflow only performs linting and formatting checks, it does not require write permissions. The `contents: read` permission is sufficient.
The `permissions` block should be added at the root level of the workflow file, ensuring it applies to all jobs in the workflow. No additional imports, methods, or definitions are required.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: add workflow permission to ui-lint

---

rockcraft.yaml

Replace the `ubuntu@24.04` base with `bare` alongside the chiseled libc6. This change brings the container image size from 138MB to 83.1MB, a 40% reduction! This image reduction makes the installation process faster and reduces the attack surface.

chore: use bare container base

---

ui/app/(core)/backup-restore/page.tsx
ui/app/(core)/data-networks/page.tsx
ui/app/(core)/operator/page.tsx

Improve card layout in:
- Operator page
- Backup & Restore page

feat: improve card layout in operator and backup pages [ui]

---

client/logs.go
client/logs_test.go
internal/api/server/api_data_networks.go
internal/api/server/api_data_networks_test.go
internal/api/server/api_operator.go
internal/api/server/api_operator_test.go
internal/api/server/api_policies.go
internal/api/server/api_policies_test.go
internal/api/server/api_routes.go
internal/api/server/api_routes_test.go
internal/api/server/api_subscribers.go
internal/api/server/api_subscribers_test.go
internal/api/server/api_users.go
internal/api/server/api_users_test.go
internal/db/routes.go

We set max number of resources for each user-created resources. For security reasons, we want to avoid the possibility of creating an unmanageable number of resources. Here we set what I think is reasonable for most private networks. If these limits turn out to be too low, we can always increase them later. But having no limits is risky.
- Subscribers: 1000
- Data Networks: 12
- Policies: 12
- Users: 50
- Supported TACs: 12
- Routes: 12
We also add log management to go client.

chore: set max number of resources

---

ui/components/DrawerLayout.tsx
ui/components/Footer.tsx

- Add `free` chip in header
- Add a footer with the copyright information. Later we will add link to website and possibly other resources.

feat: add free chip in header and copyright footer [ui]

---

ui/app/(core)/backup-restore/page.tsx
ui/app/(core)/data-networks/page.tsx
ui/app/(core)/subscribers/page.tsx

Auto refresh status so that users don't have to refresh the page to see that a subscriber went from Inactive to Active or vice-versa.

feat: auto-refresh subscriber and data network status [ui]

---

ui/app/(core)/audit-logs/page.tsx
ui/app/(core)/data-networks/page.tsx
ui/app/(core)/operator/page.tsx
ui/app/(core)/policies/page.tsx
ui/app/(core)/routes/page.tsx
ui/app/(core)/subscribers/page.tsx
ui/app/(core)/users/page.tsx

When you create a resource (ex. subscriber) for a second time in a row, the modal was pre-filled with the content of the previous creation. We don’t want that, the Create modal should be empty.

fix: open empty create modals

---

internal/api/server/authorization_middleware.go
ui/app/(core)/profile/page.tsx
ui/components/DrawerLayout.tsx

- Profile
- Log Out
It is in this same "Profile Page" that users will be able to manage their API tokens (future work).

feat: add profile page [ui]

---

internal/api/server/api_subscribers.go

We had a bug where we assumed that the PDUAddress was necessarily non-nil in the PDU session returned by the SMF. This condition was triggered whenever the UE's SD was incorrect. 
```
2025-08-22T11:40:25Z ella-core.cored[30293]: 2025-08-22T11:40:25.285Z	ERROR	gmm/sm.go:104	Error handling UL NASTransport	{"component": "AMF", "error": "error sending sm context request: create sm context request error: failed to create SM Context: error retrieving DNN information: expected sd 000001, got 102030"}
2025-08-22T11:40:28Z ella-core.cored[30293]: 2025/08/22 11:40:28 http2: panic serving 192.168.40.6:44774: runtime error: invalid memory address or nil pointer dereference
2025-08-22T11:40:28Z ella-core.cored[30293]: goroutine 236 [running]:
2025-08-22T11:40:28Z ella-core.cored[30293]: …
```

fix: add check that pdu session exists before checking for ip

---

internal/amf/ngap/dispatcher.go
internal/amf/ngap/service/service.go

When a gnb disconnects uncleanly from the core, like when using a simulator and using `ctrl-c`, the core often crashed with a segfault, due to a nil pointer dereference when trying to read the remote address. This small PR fixes the 2 instances I observed of this happening, ensuring the core stays up in such cases.

fix: Fix segfaults when SCTP connection is closed uncleanly by the remote peer
