ellanetworks/core

.github/workflows/dependabot_pr.yaml, .github/workflows/docs-publish.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-unittest.yaml, .github/workflows/go-vet.yaml, .github/workflows/integration-tests.yaml, .github/workflows/main.yml, .github/workflows/pr-lint.yml, .github/workflows/python-lint.yaml, .github/workflows/rock-build.yaml, .github/workflows/rock-publish.yaml, .github/workflows/snap-build.yaml, .github/workflows/snap-publish.yaml
Add workflow permissions
Fixes security alerts related to workflow permission.
=> chore: add workflow permissions

.github/workflows/go-lint.yaml, .github/workflows/main.yml, .github/workflows/pr-lint.yml, .github/workflows/rock-build.yaml, .github/workflows/rock-publish.yaml, .github/workflows/snap-build.yaml, .github/workflows/snap-publish.yaml
Pin non-immutable action workflow commits
=> chore: pin non-immutable action workflow commits

internal/amf/consumer/sm_context.go, internal/amf/ngap/handler.go, internal/smf/consumer/sm_policy.go, internal/smf/context/gsm_handler.go, internal/smf/context/sm_context.go, internal/smf/pdusession/api_sm_contexts_collection.go, internal/smf/pfcp/send.go, internal/smf/producer/datapath.go, internal/smf/producer/n1n2_data_handler.go, internal/smf/producer/pdu_session.go, internal/smf/producer/sm_pfcp_handling.go, internal/smf/producer/ulcl_procedure.go, tests/test_integration.py
=> fix: remove dependency on smcontext in pfcp release

.github/workflows/main.yml, README.md, docs/explanation/subscriber_authentication.md, docs/how_to/backup_and_restore.md, docs/how_to/deploy.md, mkdocs.yml, snap/snapcraft.yaml, ui/app/(auth)/layout.tsx, ui/app/(core)/layout.tsx
=> docs: add snap badge

.github/workflows/main.yml, snap/snapcraft.yaml
Use naming convention for bpf system-files  plug
=> chore: use naming convention for bpf system-files plug

.github/workflows/main.yml, .github/workflows/rock-scan.yaml
=> chore: add oci scan

internal/db/subscribers.go, internal/nms/server/api_operator.go, internal/nms/server/api_profiles.go, internal/nms/server/api_profiles_test.go
Do not allow deleting profiles with associated subscribers
Fixes #365
=> fix: do not allow deleting profiles with associated subscribers

.github/workflows/main.yml, .github/workflows/release.yaml
Publish artifacts on github release publish instead of on every push to main.
=> chore: publish artifacts on github release

ui/app/(core)/profiles/page.tsx, ui/app/(core)/subscribers/page.tsx, ui/queries/utils.tsx
Display error notifications differently from success
Fixes #368
=> fix: display error notifications differently from success

README.md, mkdocs.yml, snap/snapcraft.yaml, ui/components/DrawerLayout.tsx
=> chore: use ella networks domain

snap/snapcraft.yaml
Remove read permission from snap
=> chore: remove read permission from snap

.github/workflows/snap-publish.yaml
=> chore: allow publishing snap

docs/explanation/user_plane_packet_processing_with_ebpf.md, docs/index.md, docs/reference/config_file.md, docs/reference/data_plane_performance.md, docs/tutorials/end_to_end_network.md, mkdocs.yml
Add data plane performance results and xdp explanation.
Fixes #337
=> docs: add data plane performance results and xdp explanation

README.md, docs/explanation/obtaining_plmn_id.md, docs/explanation/operator_information.md, docs/explanation/user_plane_packet_processing_with_ebpf.md, docs/index.md, docs/overrides/main.html, mkdocs.yml
=> docs: add explanation on acquiring a PLMN ID

README.md, docs/how_to/deploy.md, docs/index.md
Add Leightweight to key features
=> docs: add Leightweight to key features

internal/amf/context/amf_ue.go, internal/amf/context/amf_ue_test.go, internal/amf/gmm/handler.go, internal/amf/gmm/sm.go, internal/amf/nas/nas_security/security.go, internal/amf/nas/nas_security/security_test.go, internal/amf/ngap/handler.go
Here we apply the following bug fixes from Aether:
- https://github.com/omec-project/amf/pull/405
- https://github.com/omec-project/amf/pull/402
- https://github.com/omec-project/amf/pull/400
- https://github.com/omec-project/amf/pull/348
They're all related to conditions that would lead the AMF to crash over there.
=> fix: pull in amf fixes from aether and add unit tests

docs/reference/logging.md, internal/api/server/api_auth.go, internal/api/server/api_backup.go, internal/api/server/api_operator.go, internal/api/server/api_profiles.go, internal/api/server/api_radios.go, internal/api/server/api_restore.go, internal/api/server/api_routes.go, internal/api/server/api_status.go, internal/api/server/api_subscribers.go, internal/api/server/api_users.go, internal/api/server/authentication.go, internal/api/server/rate_limiter_middleware.go, internal/api/server/response.go, internal/api/server/server.go, internal/logger/logger.go, internal/udm/generate_auth_data.go
- Add Latency to API logs
- Simplify writing responses
- Clearly differentiate API logs
- Add IP address to audit logs
=> chore: add more details to api and audit logs

internal/amf/ngap/message/forward_ie.go, internal/models/sm_context_create_data.go, internal/models/sm_policy_context_data.go, internal/smf/consumer/sm_policy.go, internal/smf/context/gsm_build.go, internal/smf/context/gsm_handler.go, internal/smf/context/sm_context.go, internal/smf/pdusession/api_individual_sm_context.go, internal/smf/pdusession/api_sm_contexts_collection.go, internal/smf/pfcp/send.go, internal/smf/producer/n1n2_data_handler.go, internal/smf/producer/pdu_session.go
As an artifact of the older Aether code, the SMF had a bunch of state-related behavior which unnecessarily complexified things. Here we keep it simple and get rid of all of it.
=> chore: remove state-related code in smf

internal/udm/context.go, internal/udm/generate_auth_data.go, internal/udm/generate_auth_data_test.go
improve error handling in udm authentication
=> chore: improve error handling in udm authentication

internal/ausf/functions.go, internal/ausf/ue_authentication.go, internal/kernel/routes.go, internal/logger/logger.go, internal/pcf/ampolicy.go, internal/pcf/context.go, internal/pcf/smpolicy.go, internal/smf/producer/pdu_session.go, internal/udm/context.go, internal/udm/generate_auth_data.go, internal/udm/subscriber_data_management.go, internal/util/fsm/fsm.go, internal/util/marshtojsonstring/marsh_to_json_string.go, internal/util/suci/suci.go
improve error handling in utils
=> chore: improve error handling in utils

CONTRIBUTING.md
Expand the contributing guide by stating that we welcome contribution and that they must align with the product's tenets.
=> docs: expand contributing guide

internal/amf/consumer/sm_context.go, internal/amf/context/amf_ran.go, internal/amf/gmm/handler.go, internal/amf/gmm/message/send.go, internal/amf/gmm/sm.go, internal/amf/nas/nassecurity/security.go, internal/amf/ngap/dispatcher.go, internal/amf/ngap/handler.go, internal/amf/ngap/message/send.go, internal/amf/producer/n1n2message.go, internal/smf/consumer/sm_policy.go, internal/smf/context/gsm_build.go, internal/smf/context/gsm_handler.go, internal/smf/pdusession/api_sm_contexts_collection.go, internal/smf/pfcp/send.go, internal/smf/producer/datapath.go, internal/smf/producer/n1n2_data_handler.go, internal/smf/producer/pdu_session.go, internal/smf/qos/qos_flow.go, internal/smf/qos/qos_flow_test.go, internal/smf/util/session_ambr_convert.go, internal/udm/generate_auth_data.go, internal/upf/core/display_utils.go, internal/upf/core/pfcp_session_handlers.go, internal/util/milenage/milenage.go, internal/util/milenage/milenage_test.go
Ella Core was sending too many logs, many of which should be debug, or simply not logs at all. Here we improve the logging situation a little bit. There's still lots to do here but it's way better than it was.
=> chore: improve logging

internal/logger/logger.go, internal/udm/generate_auth_data.go
This commit introduced an issue with subscriber authentication: 5c2d5004ac4de183561ab36d69b23cd122249463. Here we revert most of this change, but we keep the improved error handling.  In the future we will also want to:
- Improve unit testing around authentication
- Add integration tests that use ueransim
Fixes #497
=> fix: authentication reject 

.github/workflows/go-lint.yaml, .golangci.yml
chore: bump golangci-lint to v2.0.2
=> chore: bump golangci-lint to v2.0.2

internal/amf/ngap/dispatcher.go
dont convert empty address to string
=> fix: dont convert empty address to string

.github/workflows/go-lint.yaml
=> chore: bump golangci lint ci action

internal/models/sm_context_create_data.go, internal/smf/context/context.go, internal/smf/context/datapath.go, internal/smf/context/gsm_build.go, internal/smf/context/ngap_build.go, internal/smf/context/sm_context.go, internal/smf/context/upf.go, internal/smf/pfcp/send.go, internal/smf/producer/pdu_session.go, internal/smf/qos/qos_flow.go, internal/smf/qos/qos_flow_test.go, internal/smf/qos/qos_rule.go, internal/smf/qos/qos_rule_test.go, internal/smf/smf.go
Simplify smf and improve error handling and logging.
=> chore: simplify smf

docs/how_to/install.md, docs/reference/config_file.md, docs/reference/index.md, docs/reference/system_reqs.md, mkdocs.yml
Simplify the install guide and move the details to a new "system requirements" reference document.
=> docs: simplify installation guide

CONTRIBUTING.md, core.yaml, docs/how_to/install.md, rockcraft.yaml, snap/snapcraft.yaml
=> chore: bump node to 22/stable

.github/workflows/dependabot_pr.yaml, .github/workflows/docs-publish.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-sec.yaml, .github/workflows/go-vet.yaml, .github/workflows/integration-tests.yaml, .github/workflows/pr-lint.yml, .github/workflows/rock-build.yaml, .github/workflows/rock-publish.yaml, .github/workflows/rock-scan.yaml, .github/workflows/snap-build.yaml, .github/workflows/snap-publish.yaml, .github/workflows/ui-lint.yaml, snap/snapcraft.yaml
=> chore: bump snap base to core24 and CI runners to ubuntu 24.04

cmd/core/main.go, internal/amf/amf.go, internal/amf/ngap/service/service.go, internal/upf/upf.go
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> fix: close gracefully on SIGINT

internal/api/server/api_users.go, internal/api/server/api_users_test.go
Only allow creating the first user with an admin role.
Fixes #610
=> fix: forbid creating the first user as non-admin

docs/tutorials/end_to_end_network.md, internal/amf/context/context.go, internal/amf/deregister/deregister.go, internal/amf/gmm/sm.go, internal/api/server/api_subscribers.go, k8s/ueransim/ueransim-deployment.yaml, ui/package-lock.json, ui/package.json
When subscribers were deleted using the API/UI, the registration wouldn't be removed from the AMF and the session wouldn't be removed from the SMF. Here we make sure that cleanup occurs properly.
=> fix: remove registrations and sessions on subscriber deletion

k8s/gnbsim/gnbsim-deployment.yaml, k8s/router/router-deployment.yaml
Use the newly created ellanetworks/test-rocks to manage rocks needed to test Ella Core.
=> chore: use rocks from ellanetworks/test-rocks

ui/app/(core)/data-networks/page.tsx, ui/app/(core)/operator/page.tsx, ui/app/(core)/policies/page.tsx, ui/app/(core)/radios/page.tsx, ui/app/(core)/routes/page.tsx, ui/app/(core)/subscribers/page.tsx, ui/app/(core)/users/page.tsx, ui/components/DrawerLayout.tsx, ui/utils/theme.ts
Improve data readability in ui with:
- Space up rows
- Make title bolds
- Add background behind title row
- Use colors for actions
=> feat: improve data readability in ui
